# Generated by Django 6.0.6 on 2026-06-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('docnumber', models.CharField(max_length=11)),
                ('password', models.CharField()),
                ('creation_date', models.DateField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('docnumber',), name='account_docnumber_unique')],
            },
        ),
    ]
